issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable-all: true
  disable:
  # deprecated
    - gomnd
    - execinquery
    # unused
    - exhaustruct
    - exhaustive
    - dupl
    - nlreturn
    - nonamedreturns
    - godot # does not work with annotations.
    - perfsprint
    - musttag # broken in 1.59.
    - depguard
run:
  timeout: 5m
output:
  sort-results: true
