issues:
  exclude-rules:
    # Exclude funlen for testing files.
    - linters:
        - nonamedreturns
        - wsl
        - cyclop
        - nolintlint
      path: 'cmd/'
linters:
  enable-all: true
  disable:
    - maligned
    - scopelint
    - interfacer
    - golint
    - exhaustruct
    - exhaustive
    - exhaustivestruct
    - dupl
    - nlreturn
    - nonamedreturns
    - varnamelen
run:
  timeout: 5m