issues:
  exclude-rules:
    # Exclude funlen for testing files.
    - linters:
        - nonamedreturns
        - wsl
        - cyclop
        - nolintlint
      path: 'cmd/'
linters:
  enable-all: true
  disable:
  # deprecated
    - maligned
    - scopelint
    - interfacer
    - golint
    - exhaustivestruct
    - nosnakecase
    - structcheck
    - deadcode
    - varcheck
    - ifshort
    # unused
    - exhaustruct
    - exhaustive
    - dupl
    - nlreturn
    - nonamedreturns
    - varnamelen
    - godot
    # unneeded (broken because of generics)
    - rowserrcheck
    - wastedassign
    - sqlclosecheck
run:
  timeout: 5m