issues:
  exclude-rules:
    # Exclude funlen for testing files.
    - linters:
        - nonamedreturns
        - wsl
        - cyclop
        - nolintlint
      path: 'cmd/'
linters:
  enable-all: true
  disable:
  # deprecated
    - gomnd
    - execinquery
    # unused
    - exhaustruct
    - exhaustive
    - dupl
    - nlreturn
    - nonamedreturns
    - varnamelen
    - godot # does not work with annotations.
    - perfsprint
    - musttag # broken in 1.59.
    - depguard
    - tagalign
run:
  timeout: 5m