issues:
  exclude-rules:
    # Exclude funlen for testing files.
    - linters:
        - nonamedreturns
        - wsl
        - cyclop
        - nolintlint
      path: 'cmd/'
linters:
  enable-all: true
  disable:
  # deprecated
    - gomnd
    - execinquery
    # unused
    - exhaustruct
    - exhaustive
    - dupl
    - nlreturn
    - nonamedreturns
    - varnamelen
    - godot
    - perfsprint
    # unneeded (broken because of generics)
    - rowserrcheck
    - wastedassign
    - sqlclosecheck
    #- revive # TODO: fix this one.
    - musttag # broken in 1.52.
    - depguard
    - tagalign
run:
  timeout: 5m