# Powered by Application Builder: https://github.com/golift/application-builder
env:
  - MAKEBUILD=deb
jobs:
  include:
  - os: osx
    if: tag IS present
    osx_image: xcode13.2
    language: go
    go: 1.19.x
  - if: tag IS NOT present AND branch != unstable
    os: linux
    dist: bionic
    services: docker
    language: go
    go: 1.19.x
  - if: tag IS present OR branch = unstable
    os: linux
    dist: bionic
    services: docker
    language: go
    go: 1.19.x
    env: MAKEBUILD=release
git:
  depth: false
addons:
  homebrew:
    packages:
    - upx
  apt:
    packages:
    - ruby-dev
    - rpm
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - zip
    - debsigs
    - gnupg
    - upx
install:
  - mkdir -p $(go env GOPATH)/bin
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.0
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm install 2.6.0; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm 2.6.0 do gem install --no-document fpm -v 1.11.0; fi
  - make generate
before_script:
  # Create your own deploy key, tar it, and encrypt the file to make this work. Optionally add a bitly_token file to the archive.
  - openssl aes-256-cbc -K $encrypted_772fc4772f04_key -iv $encrypted_772fc4772f04_iv -in .secret_files.tar.enc -out .secret_files.tar -d
  - tar -xf .secret_files.tar
  - gpg --import gpg.signing.key
  - rm -f gpg.signing.key .secret_files.tar
  - source settings.sh
script:
  # Test Go.
  - make test
  # Test Docker. Docker rate limits and breaks my builds.
  - #if [ "$TRAVIS_OS_NAME" == "linux" ]; then make docker; fi
  # Test built docker image.
  - #if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run $BINARY -v 2>&1 | grep -Eq "^$BINARY,? v.*$VERSION"; fi
  # Build everything
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm 2.6.0 do make $MAKEBUILD; fi
  # Build mac binary or image.
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make dmg; fi
  # Test homebrew (with make install).
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make install VERSION=$VERSION ITERATION=$ITERATION PREFIX=/tmp/ab-$VERSION ETC=/tmp/ab-$VERSION/etc; fi
after_success:
  # Display Release Folder
  - ls -l release/
  # Setup the ssh client so we can clone and push to the homebrew formula repo.
  # You must put github_deploy_file into .secret_files.tar.enc
  # This is an ssh key added to your homebrew forumla repo.
  - |
    mkdir -p $HOME/.ssh
    declare -r HB_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    [ ! -f github_deploy_key ] || (mv github_deploy_key "${HB_FILE}" \
      && chmod 600 "$HB_FILE" \
      && printf "%s\n" \
        "Host github.com" \
        "  HostName github.com" \
        "  IdentityFile ${HB_FILE}" \
        "  StrictHostKeyChecking no" \
        "  LogLevel ERROR" >> $HOME/.ssh/config)
    declare -r AU_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    [ ! -f aur_deploy_key ] || (mv aur_deploy_key "${AU_FILE}" \
      && chmod 600 "${AU_FILE}" \
      && printf "%s\n" \
        "Host github.com-aurepo" \
        "  HostName github.com" \
        "  IdentityFile ${AU_FILE}" \
        "  StrictHostKeyChecking no" \
        "  LogLevel ERROR" >> $HOME/.ssh/config)
deploy:
  # Unstable (master pushes).
  - provider: packagecloud
    repository: unstable
    username: golift
    token:
      secure: PuwkeI7VlBBEpg9b6KsQy4lDEt10dQuDsZ1qVQBEllqUmpfRbn2EGk8b7nTiRTjfCVT9u1FX4I43MN/IBdgJPg9fI3YQcg5/lbEUrqDLtgo/MsP8pvMnXuhU+JuROdOHJP7/mVJrOOjDJBykTkHgtHhUcd7DcgNL5wytVdxU9szbeSns1MDK6ZPN2zxGYj9H7hmGGPWXSyNFwl87fL9629KEXUh7Ad85/G/EACdv1USz3ZHjOVt7KaUuaK/tnlyygH1WH5ynV5CRuVgcIivGPjsLqbPYGv1OUbg2bq6JcLBgXivmiN+CI6C0LjlZEgYxaEw0ynyCbBTGkRRWSez5LiMsGHfPQynrw7MA6ZCkzfdVHCPT4HSdTCTc6g4kLvf7q2HRVeED07e8RFaNWrxJyOCE05L5PhKHpTilkJjrFVV19hluM95L1xnNEGWRpkJxjrFqwf7l2Y425+pTYwa2wrLdtULkGyLA2Wf7EHqGY2f9LZ3g32In1/do34MCDO/STUBpwIR+PqvATmqbVM8/otq1wmJD5yGmb0U9dp1CPZ3jdKjzlVJ8x7FLVwXhIKZJIh7RdOm7zsfmWvRvQkx0MyFtA4eoekYig+AmJEA+fCCqBQgdB1FHKRoElDUCRw3nyhhYamt6rDdqPxVPVHi87iRdg+OcUEtPNFrUxZDaJHU=
    dist: ubuntu/focal
    local-dir: release
    package_glob: "*.deb"
    skip_cleanup: true
    cleanup: false
    on:
      branch: unstable
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: packagecloud
    repository: unstable
    username: golift
    token:
      secure: PuwkeI7VlBBEpg9b6KsQy4lDEt10dQuDsZ1qVQBEllqUmpfRbn2EGk8b7nTiRTjfCVT9u1FX4I43MN/IBdgJPg9fI3YQcg5/lbEUrqDLtgo/MsP8pvMnXuhU+JuROdOHJP7/mVJrOOjDJBykTkHgtHhUcd7DcgNL5wytVdxU9szbeSns1MDK6ZPN2zxGYj9H7hmGGPWXSyNFwl87fL9629KEXUh7Ad85/G/EACdv1USz3ZHjOVt7KaUuaK/tnlyygH1WH5ynV5CRuVgcIivGPjsLqbPYGv1OUbg2bq6JcLBgXivmiN+CI6C0LjlZEgYxaEw0ynyCbBTGkRRWSez5LiMsGHfPQynrw7MA6ZCkzfdVHCPT4HSdTCTc6g4kLvf7q2HRVeED07e8RFaNWrxJyOCE05L5PhKHpTilkJjrFVV19hluM95L1xnNEGWRpkJxjrFqwf7l2Y425+pTYwa2wrLdtULkGyLA2Wf7EHqGY2f9LZ3g32In1/do34MCDO/STUBpwIR+PqvATmqbVM8/otq1wmJD5yGmb0U9dp1CPZ3jdKjzlVJ8x7FLVwXhIKZJIh7RdOm7zsfmWvRvQkx0MyFtA4eoekYig+AmJEA+fCCqBQgdB1FHKRoElDUCRw3nyhhYamt6rDdqPxVPVHi87iRdg+OcUEtPNFrUxZDaJHU=
    dist: el/6
    local-dir: release
    package_glob: "*.rpm"
    skip_cleanup: true
    cleanup: false
    on:
      branch: unstable
      condition: "$TRAVIS_OS_NAME = linux"
  # Stable packages (releases).
  - provider: packagecloud
    repository: pkgs
    username: golift
    token:
      secure: PuwkeI7VlBBEpg9b6KsQy4lDEt10dQuDsZ1qVQBEllqUmpfRbn2EGk8b7nTiRTjfCVT9u1FX4I43MN/IBdgJPg9fI3YQcg5/lbEUrqDLtgo/MsP8pvMnXuhU+JuROdOHJP7/mVJrOOjDJBykTkHgtHhUcd7DcgNL5wytVdxU9szbeSns1MDK6ZPN2zxGYj9H7hmGGPWXSyNFwl87fL9629KEXUh7Ad85/G/EACdv1USz3ZHjOVt7KaUuaK/tnlyygH1WH5ynV5CRuVgcIivGPjsLqbPYGv1OUbg2bq6JcLBgXivmiN+CI6C0LjlZEgYxaEw0ynyCbBTGkRRWSez5LiMsGHfPQynrw7MA6ZCkzfdVHCPT4HSdTCTc6g4kLvf7q2HRVeED07e8RFaNWrxJyOCE05L5PhKHpTilkJjrFVV19hluM95L1xnNEGWRpkJxjrFqwf7l2Y425+pTYwa2wrLdtULkGyLA2Wf7EHqGY2f9LZ3g32In1/do34MCDO/STUBpwIR+PqvATmqbVM8/otq1wmJD5yGmb0U9dp1CPZ3jdKjzlVJ8x7FLVwXhIKZJIh7RdOm7zsfmWvRvQkx0MyFtA4eoekYig+AmJEA+fCCqBQgdB1FHKRoElDUCRw3nyhhYamt6rDdqPxVPVHi87iRdg+OcUEtPNFrUxZDaJHU=
    dist: ubuntu/focal
    local-dir: release
    package_glob: "*.deb"
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: packagecloud
    repository: pkgs
    username: golift
    token:
      secure: PuwkeI7VlBBEpg9b6KsQy4lDEt10dQuDsZ1qVQBEllqUmpfRbn2EGk8b7nTiRTjfCVT9u1FX4I43MN/IBdgJPg9fI3YQcg5/lbEUrqDLtgo/MsP8pvMnXuhU+JuROdOHJP7/mVJrOOjDJBykTkHgtHhUcd7DcgNL5wytVdxU9szbeSns1MDK6ZPN2zxGYj9H7hmGGPWXSyNFwl87fL9629KEXUh7Ad85/G/EACdv1USz3ZHjOVt7KaUuaK/tnlyygH1WH5ynV5CRuVgcIivGPjsLqbPYGv1OUbg2bq6JcLBgXivmiN+CI6C0LjlZEgYxaEw0ynyCbBTGkRRWSez5LiMsGHfPQynrw7MA6ZCkzfdVHCPT4HSdTCTc6g4kLvf7q2HRVeED07e8RFaNWrxJyOCE05L5PhKHpTilkJjrFVV19hluM95L1xnNEGWRpkJxjrFqwf7l2Y425+pTYwa2wrLdtULkGyLA2Wf7EHqGY2f9LZ3g32In1/do34MCDO/STUBpwIR+PqvATmqbVM8/otq1wmJD5yGmb0U9dp1CPZ3jdKjzlVJ8x7FLVwXhIKZJIh7RdOm7zsfmWvRvQkx0MyFtA4eoekYig+AmJEA+fCCqBQgdB1FHKRoElDUCRw3nyhhYamt6rDdqPxVPVHi87iRdg+OcUEtPNFrUxZDaJHU=
    dist: el/6
    local-dir: release
    package_glob: "*.rpm"
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  # Upload built files to github too.
  - provider: releases
    api_key:
      secure: cpzdD1v60YXQ4es8AAe2rv99TI1527htcSgoTrJh/tJnPbCFwzEPH7DcwB/gCEOEjrU2Mry77cx9n+1emDcPf2Z7wk6Tt77un7K1VRhI5PDZ7XsYhRFXpF837O4ZkIJHHB8nrPkiMVjZGziAin9s1IvWZF3nDzDdUsOjrkjhbu2OSf1Fji95DkpMgqJskCdZAru1+OTeO5lZyQxZP/SNIJeWy0Q3qL9c5IQ+H1tNbyKULHIIi1biWIOg/yeICbhsa5pqu2jLlOvjk9ZH71VA2jiFP8o3nBslXeAWEPjUXehnKWxpShH3oF3KfK58sQgz8vN4ZZ+acvlAcQovKgJRGs72xqF9fd+oFZdihx5GWWtZwVlsHtOAh1oiBcPWryjSIA7QXIIgUVH1hu06mosv9d1JWYbr8fPsubMkzwUvlGbk9iSQqieN1A5WUGiD3ZM0boX2cMvJZ+wmeFG+3LFkSG/n9kDDK81zRR6YlxEjDJEriGHPBA4tABeA0iNwkWI1GStUiZZOefbixsWMNSRsriohMAOqmEzxqZp9m23baRCXtSpd2LvlpXCs8dZtqO7U2T8dSYbVAN8JJsiPKGH0ZGko5/XG3l9B0Sg0SCDFT84tq/dPpkJZHDA/wMoxFO+fyNwexpcsnd+d8XT0ub0vrm1O/5MZ2BKgWDQu9uvWXw8=
    overwrite: true
    skip_cleanup: true
    cleanup: false
    file_glob: true
    file: release/*
    on:
      tags: true
  # Upload homebrew formula file to a special repo.
  - provider: script
    script: bash scripts/formula-deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
  # Upload aur PKGBUILD file to a special repo.
  - provider: script
    script: bash scripts/aur-deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
