name: test-and-lint
on:
  push:
    branches:
      - unstable
  pull_request:
    branches:
    - main
permissions:
  contents: read
jobs:
  # Runs `go test` against 3 operating systems.
  gotest:
    strategy:
      matrix:
        os: [macos, windows, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3
      - name: go-generate
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          go install github.com/kevinburke/go-bindata/...@latest
          PATH=${PATH}:$(go env GOPATH)/bin go generate ./...
      - name: go-test
        run: |
          go test ./pkg/...
  # Runs golangci-lint on macos against freebsd and macos.
  golangci-darwin:
    strategy:
      matrix:
        os: [darwin, freebsd]
    name: golangci-lint
    runs-on: macos-latest
    env:
      GOOS: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - name: go-generate
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          go install github.com/kevinburke/go-bindata/...@latest
          PATH=${PATH}:$(go env GOPATH)/bin go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
  # Runs golangci-lint on linux against linux and windows.
  golangci-linux:
    strategy:
      matrix:
        os: [windows, linux]
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - name: go-generate
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          go install github.com/kevinburke/go-bindata/...@latest
          PATH=${PATH}:$(go env GOPATH)/bin go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
  homebrew-test:
    name: test-homebrew-install
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - name: go-generate
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          go install github.com/kevinburke/go-bindata/...@latest
          PATH=${PATH}:$(go env GOPATH)/bin go generate ./...
      - name: make-install
        run: |
          TMP=$(mktemp -d)
          go install github.com/davidnewhall/md2roff@v0.0.1
          make install VERSION=0.0.1 ITERATION=240 PREFIX=$TMP ETC=$TMP/etc
  release-test:
    name: test-make-release
    runs-on: ubuntu-latest
    env:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
        with:
          fetch-depth: ''
      - name: go-generate
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          go install github.com/kevinburke/go-bindata/...@latest
          PATH=${PATH}:$(go env GOPATH)/bin go generate ./...
      - name: make-release
        run: |
          sudo apt install -y rpm fakeroot zip debsigs gnupg
          sudo gem install --no-document fpm
          echo "${GPG_SIGNING_KEY}" | gpg --import -
          go install github.com/akavel/rsrc@latest
          go install github.com/davidnewhall/md2roff@v0.0.1
          make release