name: release-aur-and-homebrew
on:
  workflow_run:
    workflows: ["build-and-release"]
    types: [completed]
permissions:
  contents: read
jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      - name: hah
      - run: echo "it works"

  archlinux-aur:
    if: startsWith(github.ref, 'refs/tags/v') && ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: deploy-aur
        run: bash init/archlinux/aur-deploy.sh
        env:
          AUR_DEPLOY_KEY: ${{ secrets.AUR_DEPLOY_KEY }}

  homebrew-formula:
    if: startsWith(github.ref, 'refs/tags/v') && ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: make-homebrew
        run: bash init/homebrew/formula-deploy.sh
        env:
          HOMEBREW_DEPLOY_KEY: ${{ secrets.HOMEBREW_DEPLOY_KEY }}
