name: build-and-release
on:
  push:
    branches:
      - unstable
      - main
    tags:
      - v*
  pull_request:
    branches:
    - main
    - unstable
    - development
permissions:
  contents: read
jobs:
  macapp-test:
    # description: "Builds and signs a macOS app then packages it in a notarized DMG."
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/unstable'
    outputs:
      packages: ${{ steps.release.outputs.packages }}
    name: test-make-signdmg
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # we need the whole thing so we can count commits.
          fetch-depth: '0'
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: go-generate
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          go install github.com/kevinburke/go-bindata/...@latest
          go generate ./...
      - name: make-signdmg
        env:
          APPLE_SIGNING_KEY: ${{ secrets.APPLE_SIGNING_KEY }}
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
        id: release
        run: |
          brew install mitchellh/gon/gon jq
          make signdmg
          echo "packages=$(ls release/*.dmg | jq -R '.' | jq -sc)" >> $GITHUB_OUTPUT
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dmg-release
          path: release

  release-test:
    # description: "Builds all the Notifiarr client binaries and packages for a release."
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/unstable' || github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.release.outputs.version }}
    name: test-make-release
    runs-on: ubuntu-latest
    env:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          # we need the whole thing so we can count commits.
          fetch-depth: '0'
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: go-generate
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          go install github.com/kevinburke/go-bindata/...@latest
          # make release will clean and generate so do not do it here.
      - name: make-release
        id: release
        run: |
          sudo apt install -y rpm fakeroot zip debsigs gnupg jq 
          sudo gem install --no-document fpm
          echo "${GPG_SIGNING_KEY}" | gpg --import -
          go install github.com/akavel/rsrc@latest
          go install github.com/davidnewhall/md2roff@v0.0.1
          make release
          source settings.sh ; echo "version=${VERSION}-${ITERATION}" >> $GITHUB_OUTPUT
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release

  deploy-unstable-unstable:
    # description: "Uploads pre-built binaries to unstable.notifiarr.app."
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/unstable'
    strategy:
      matrix:
        files: [release, dmg-release]
    needs:
      - release-test
      - macapp-test
    name: deploy-unstable
    runs-on: ubuntu-latest
    steps:
      - name: Download release files
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.files }}
      - name: Upload files to unstable.notifiarr.app
        run: >-
          for file in *.{zip,dmg,gz}; do
            [ -f "$file" ] || continue;
            echo "Uploading: ${file}";
            curl -sSH "X-API-KEY: ${{ secrets.UNSTABLE_UPLOAD_KEY }}" "https://unstable.notifiarr.app/upload.php" -F "file=@${file}";
            versionfile="${{needs.release-test.outputs.version}};filename=${file}.txt;type=text/plain";
            curl -sSH "X-API-KEY: ${{ secrets.UNSTABLE_UPLOAD_KEY }}" "https://unstable.notifiarr.app/upload.php" -F "file=${versionfile}";
          done

  deploy-unstable-packagecloud:
    # description: "Uploads pre-built RPM and DEB packages to packagecloud.io/golift"
    if: github.ref == 'refs/heads/unstable'
    needs: release-test
    name: deploy-unstable-packagecloud
    runs-on: ubuntu-latest
    steps:
      - name: Download release files
        uses: actions/download-artifact@v2
        with:
          name: release
      - uses: golift/upload-packagecloud@v1
        with:
          userrepo: golift/unstable
          apitoken: ${{ secrets.PACKAGECLOUD_TOKEN }}
          packages: .
          rpmdists: el/7
          debdists: ubuntu/focal

  deploy-packagecloud:
    # description: "Uploads pre-built RPM and DEB packages to packagecloud.io/golift"
    if: startsWith(github.ref, 'refs/tags/v')
    needs: release-test
    name: deploy-release-packagecloud
    runs-on: ubuntu-latest
    steps:
      - name: Download release files
        uses: actions/download-artifact@v2
        with:
          name: release
      - uses: golift/upload-packagecloud@v1
        with:
          userrepo: golift/pkgs
          apitoken: ${{ secrets.PACKAGECLOUD_TOKEN }}
          packages: .
          rpmdists: el/7
          debdists: ubuntu/focal