name: test-and-lint
on:
  push:
    branches:
      - unstable
  pull_request:
    types: [opened, reopened, edited]
permissions:
  contents: read
jobs:
  gotest:
    strategy:
      matrix:
        go: [1.19]
        os: [windows, darwin, linux, freebsd]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: go-test
        run: |
          GOOS=${{ matrix.os }} go test ./...
  golangci:
    strategy:
      matrix:
        go: [1.19]
        os: [windows, darwin, linux, freebsd]
    name: lint
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48