name: test-and-lint
on:
  push:
    branches:
      - unstable
  pull_request:
    types: [opened, reopened, edited]
permissions:
  contents: read
jobs:

  gotest-windows:
    runs-on: windows-latest
    steps: &gotest-test
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: go-test
        run: |
          go test ./pkg/...

  gotest-macos:
    runs-on: macos-latest
    steps: 
      <<: *gotest-test

  gotest-linux:
    runs-on: ubuntu-latest
    steps: 
      <<: *gotest-test


  golangci-macos:
    strategy:
      matrix:
        os: [darwin, freebsd]
    name: golangci-lint
    runs-on: macos-latest
    env:
      GOOS: ${{ matrix.os }}
    steps: &golangci-lint-test
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48

  golangci-linux:
    strategy:
      matrix:
        os: [windows, linux]
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
    steps: 
      <<: *golangci-lint-test