name: Test

on:
  push:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-go@v3

      - name: Make test
        run: |
          make test
        env:
          PATH: /bin:/usr/bin:/home/runner/go/bin